baseURL = "//dcb.lu/"
canonifyurls = true
languageCode = "en-us"
title = "dcb.lu"
theme = "hugo-theme-cactus"
Copyright = "Dan Bolan"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[params]
colortheme = "light"
showallpostsonhomepage = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "arduino"
    tabWidth = 4
